import { defineStore } from 'pinia';
import { ref, computed } from 'vue';
import { Session, Message, CliCommandStatus, ResumeSession } from '../types';
import { api, isElectron } from '../services/api';

export const useSessionsStore = defineStore('sessions', () => {
  const sessions = ref<Session[]>([]);
  const activeSessionId = ref<string | null>(null);
  const messages = ref<Message[]>([]);
  const viewMode = ref<'terminal' | 'chat'>('chat');
  
  // CLI status
  const cliStatus = ref<'idle' | 'running' | 'stopped' | 'error'>('idle');
  const cliError = ref<string | null>(null);
  const cliPid = ref<number | null>(null);
  const cliCommandInfo = ref<CliCommandStatus | null>(null);
  
  // UI states
  const isSidebarOpen = ref(true);
  const isSettingsModalOpen = ref(false);
  const isNewSessionModalOpen = ref(false);
  const isResumeModalOpen = ref(false);
  const resumeSessions = ref<ResumeSession[]>([]);
  const availableModels = ref<string[]>([]);
  const sessionModels = ref<Record<string, string>>({});
  const isExporting = ref(false);
  const isLoading = ref(false);
  const liveActivityText = ref('Analiza kodu i generowanie myśli...');
  const isCliProcessing = ref(false);

  // Terminal raw data emitter for active session
  const terminalDataQueue = ref<string[]>([]);
  const onTerminalDataCallback = ref<((data: string) => void) | null>(null);

  const activeSession = computed(() => {
    return sessions.value.find((s) => s.id === activeSessionId.value) || null;
  });

  // Check CLI installation
  const checkCli = async () => {
    const res = await api.agy.checkCommand();
    cliCommandInfo.value = res;
    if (!res.found && res.error) {
      cliStatus.value = 'error';
      cliError.value = res.error;
    }
  };

  const loadSessions = async () => {
    isLoading.value = true;
    try {
      await checkCli();
      const list = await api.sessions.list();
      sessions.value = list;
      if (list.length > 0 && !activeSessionId.value) {
        await selectSession(list[0].id);
      }
      
      if (api.agy?.listModels) {
        const res = await api.agy.listModels();
        if (res?.success && res.models) {
          availableModels.value = res.models;
          if (res.currentModel && activeSessionId.value) {
            sessionModels.value[activeSessionId.value] = res.currentModel;
          }
        }
      }
    } finally {
      isLoading.value = false;
    }
  };

  // Select session
  const selectSession = async (id: string) => {
    activeSessionId.value = id;
    cliStatus.value = 'idle';
    cliPid.value = null;
    cliError.value = null;
    terminalDataQueue.value = [];
    
    try {
      const { session, messages: msgs } = await api.sessions.select(id);
      messages.value = msgs;
      
      // Update session in list
      const idx = sessions.value.findIndex((s) => s.id === id);
      if (idx !== -1) sessions.value[idx] = session;

      // Sync title just in case it was generated by the CLI while we were offline
      const syncRes = await api.agy.syncTitle({ sessionId: id });
      if (syncRes.success && syncRes.title) {
        if (activeSession.value) activeSession.value.title = syncRes.title;
        if (idx !== -1) sessions.value[idx].title = syncRes.title;
      }
      
      if (api.agy?.listModels) {
        const res = await api.agy.listModels();
        if (res?.success && res.models) {
          availableModels.value = res.models;
          if (res.currentModel) {
            sessionModels.value[id] = res.currentModel;
          }
        }
      }

      // Start CLI process for this session
      await startCli();
    } catch (e: any) {
      console.error('Error selecting session:', e);
    }
  };

  // Create session
  const createSession = async (title: string, cwd?: string) => {
    const newSess = await api.sessions.create({ title, cwd });
    sessions.value.unshift(newSess);
    isNewSessionModalOpen.value = false;
    await selectSession(newSess.id);
  };

  // Load resume sessions from Antigravity CLI (/resume)
  const loadResumeSessions = async () => {
    resumeSessions.value = await api.agy.listResumeSessions();
  };

  // Import session from Antigravity CLI (/resume)
  const importResumeSession = async (resSess: ResumeSession) => {
    // Check if already imported
    const existing = sessions.value.find((s) => s.id === resSess.id || s.antigravity_id === resSess.id);
    if (existing) {
      isResumeModalOpen.value = false;
      await selectSession(existing.id);
      return;
    }
    const newSess = await api.sessions.create({
      title: resSess.title,
      cwd: resSess.cwd,
      antigravity_id: resSess.id,
    });
    sessions.value.unshift(newSess);
    isResumeModalOpen.value = false;
    await selectSession(newSess.id);
  };

  // Delete session
  const deleteSession = async (id: string) => {
    await api.sessions.delete(id);
    sessions.value = sessions.value.filter((s) => s.id !== id);
    if (activeSessionId.value === id) {
      if (sessions.value.length > 0) {
        await selectSession(sessions.value[0].id);
      } else {
        activeSessionId.value = null;
        messages.value = [];
        cliStatus.value = 'idle';
      }
    }
  };

  // Change CWD
  const changeCwd = async () => {
    if (!activeSessionId.value) return;
    const selected = await api.dialog.selectFolder();
    if (selected) {
      await api.sessions.updateCwd(activeSessionId.value, selected);
      if (activeSession.value) {
        activeSession.value.cwd = selected;
      }
      // Restart CLI with new CWD
      await startCli();
    }
  };

  // Start CLI
  const startCli = async () => {
    if (!activeSessionId.value || !activeSession.value) return;
    
    cliStatus.value = 'running';
    cliError.value = null;

    const res = await api.agy.startSession({
      sessionId: activeSessionId.value,
      cwd: activeSession.value.cwd || undefined,
    });

    if (res.success) {
      cliStatus.value = 'running';
      cliPid.value = res.pid || null;
      if (res.command && activeSession.value) {
        activeSession.value.cli_command = res.command;
      }
    } else {
      cliStatus.value = 'error';
      cliError.value = res.error || 'Nie udało się uruchomić procesu Antigravity CLI.';
    }
  };

  // Stop CLI
  const stopCli = async () => {
    if (!activeSessionId.value) return;
    await api.agy.stop({ sessionId: activeSessionId.value });
    cliStatus.value = 'stopped';
    cliPid.value = null;
  };

  // Send prompt
  const sendPrompt = async (text: string) => {
    if (!activeSessionId.value) return;
    
    isCliProcessing.value = true;
    liveActivityText.value = 'Wysyłanie instrukcji...';

    // If CLI stopped or errored, try starting it first
    if (cliStatus.value !== 'running') {
      await startCli();
    }

    const trimmed = text.trim();
    const isModelCommand = trimmed.startsWith('/model ') || trimmed === '/model';
    
    // Add user message to local UI state immediately, except for model changes
    if (!isModelCommand) {
      const tempId = 'msg_' + Date.now();
      messages.value.push({
        id: tempId,
        session_id: activeSessionId.value,
        role: 'user',
        content: trimmed,
        raw_output: trimmed,
        created_at: new Date().toISOString(),
      });
    }

    // Send to backend
    const res = await api.agy.send({ sessionId: activeSessionId.value, text: trimmed });
    if (!res.success && res.error) {
      messages.value.push({
        id: 'err_' + Date.now(),
        session_id: activeSessionId.value,
        role: 'system',
        content: `⚠️ **Błąd wysyłania komendy:** ${res.error}`,
        raw_output: res.error,
        created_at: new Date().toISOString(),
      });
    } else {
      // Reload messages after brief delay to catch backend IDs
      setTimeout(async () => {
        if (activeSessionId.value) {
          messages.value = await api.messages.list(activeSessionId.value);
        }
      }, 300);
    }
  };

  // Clear display (does not delete from DB without separate confirmation as requested!)
  const clearDisplay = () => {
    messages.value = [];
    terminalDataQueue.value.push('\x1b[2J\x1b[H'); // ANSI clear screen
    if (onTerminalDataCallback.value) {
      onTerminalDataCallback.value('\x1b[2J\x1b[H');
    }
  };

  // Export Markdown
  const exportMarkdown = async () => {
    if (!activeSessionId.value) return;
    isExporting.value = true;
    try {
      const res = await api.export.markdown(activeSessionId.value);
      if (res.success && res.path) {
        alert(`✅ Pomyślnie wyeksportowano sesję do pliku:\n${res.path}`);
      } else if (!res.canceled && res.error) {
        alert(`❌ Błąd eksportu: ${res.error}`);
      }
    } finally {
      isExporting.value = false;
    }
  };

  // Register listeners
  let cliIdleTimeout: any = null;
  const setupListeners = () => {
    api.agy.onOutput(({ sessionId, data }) => {
      if (sessionId === activeSessionId.value) {
        if (onTerminalDataCallback.value) {
          onTerminalDataCallback.value(data);
        } else {
          terminalDataQueue.value.push(data);
        }

        // Extract live activity status for Chat View indicator
        const cleanChunk = data.replace(/\x1B\[[0-9;]*[a-zA-Z]/g, '').trim();
        if (cleanChunk.includes('Thought for')) {
          const match = cleanChunk.match(/Thought for [^\n\r]*/);
          if (match) liveActivityText.value = `🧠 ${match[0]}`;
        } else if (cleanChunk.includes('view_file') || cleanChunk.includes('read_file')) {
          liveActivityText.value = '📂 Odczytywanie i analiza plików...';
        } else if (cleanChunk.includes('replace_file') || cleanChunk.includes('write_file') || cleanChunk.includes('multi_replace')) {
          liveActivityText.value = '✍️ Edytowanie kodu i wprowadzanie zmian...';
        } else if (cleanChunk.includes('run_command')) {
          liveActivityText.value = '⚡ Wykonywanie polecenia w terminalu...';
        } else if (cleanChunk.includes('grep_search') || cleanChunk.includes('list_dir')) {
          liveActivityText.value = '🔍 Przeszukiwanie struktury projektu...';
        } else if (cleanChunk.length > 5 && !cleanChunk.includes('? for shortcuts')) {
          // If it's not a known tool, just assume it's generating the markdown response or thinking
          liveActivityText.value = '✨ Generowanie odpowiedzi...';
        }

        // Live activity status - ONLY update text if already processing.
        // We do NOT set it to true here to avoid triggering the loading indicator 
        // when simply opening a chat or receiving initial terminal buffers.
        if (cleanChunk.length > 0 && isCliProcessing.value) {
          liveActivityText.value = liveActivityText.value || 'Analiza kodu i generowanie myśli...';
        }
        
        // Smart idle detection: if the output contains the typical CLI prompt characters 
        // waiting for user input, we know the AI is done processing.
        // We also check for 'GravityDesk' or terminal paths to turn off on initial load just in case.
        if (cleanChunk.includes('? ') || cleanChunk.includes('❯ ') || cleanChunk.includes('projekt?')) {
          isCliProcessing.value = false;
        }

        // Debounce refreshing chat messages if in chat view mode
        if (viewMode.value === 'chat') {
          debounceRefreshMessages();
        }
      }
    });

    api.agy.onStatusChange(({ sessionId, status, pid, error }) => {
      if (sessionId === activeSessionId.value) {
        cliStatus.value = status as any;
        if (status !== 'running') isCliProcessing.value = false;
        if (pid) cliPid.value = pid;
        if (error) cliError.value = error;
      }
    });
  };

  let refreshTimeouts: any[] = [];
  const debounceRefreshMessages = () => {
    refreshTimeouts.forEach(clearTimeout);
    refreshTimeouts = [];
    
    // AI writes to stdout, then saves transcript to disk.
    // We poll the backend a few times but we MUST debounce these properly to avoid freezing the app!
    const pollDelays = [200, 800, 2000, 4000, 8000, 15000];
    
    pollDelays.forEach(delay => {
      const t = setTimeout(async () => {
        if (activeSessionId.value && viewMode.value === 'chat') {
          messages.value = await api.messages.list(activeSessionId.value);
          
          if (activeSession.value && delay >= 4000) {
            const res = await api.agy.syncTitle({ sessionId: activeSessionId.value });
            if (res.success && res.title) {
              activeSession.value.title = res.title;
              const sess = sessions.value.find(s => s.id === activeSessionId.value);
              if (sess) sess.title = res.title;
            }
          }
        }
      }, delay);
      refreshTimeouts.push(t);
    });
  };

  // Bind terminal data callback
  const registerTerminalCallback = (cb: (data: string) => void) => {
    onTerminalDataCallback.value = cb;
    while (terminalDataQueue.value.length > 0) {
      const chunk = terminalDataQueue.value.shift();
      if (chunk) cb(chunk);
    }
  };

  return {
    sessions,
    activeSessionId,
    activeSession,
    messages,
    viewMode,
    cliStatus,
    cliError,
    cliPid,
    cliCommandInfo,
    isSidebarOpen,
    isSettingsModalOpen,
    isNewSessionModalOpen,
    isResumeModalOpen,
    resumeSessions,
    availableModels,
    sessionModels,
    isExporting,
    isLoading,
    liveActivityText,
    isCliProcessing,
    isElectron,
    loadSessions,
    loadResumeSessions,
    selectSession,
    createSession,
    importResumeSession,
    deleteSession,
    changeCwd,
    startCli,
    stopCli,
    sendPrompt,
    clearDisplay,
    exportMarkdown,
    setupListeners,
    registerTerminalCallback,
  };
});
